CREATE TABLE `applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`customerId` varchar(100) NOT NULL,
	`businessName` varchar(255) NOT NULL,
	`businessType` varchar(100) NOT NULL,
	`businessAge` int NOT NULL,
	`address` text NOT NULL,
	`phone` varchar(50) NOT NULL,
	`email` varchar(320),
	`monthlyRevenue` decimal(15,2) NOT NULL,
	`monthlyExpenses` decimal(15,2) NOT NULL,
	`existingDebt` decimal(15,2) NOT NULL,
	`collateralValue` decimal(15,2) NOT NULL,
	`requestedAmount` decimal(15,2) NOT NULL,
	`loanPurpose` text NOT NULL,
	`legalDocuments` json NOT NULL,
	`businessShariaCompliant` enum('yes','no','partial') NOT NULL,
	`shariaComplianceNotes` text,
	`environmentalPractices` text,
	`socialImpact` text,
	`governanceQuality` enum('excellent','good','fair','poor') NOT NULL,
	`status` enum('pending','assessed','approved','rejected') NOT NULL DEFAULT 'pending',
	`submittedBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int NOT NULL,
	`sustainableFinanceScore` decimal(5,2) NOT NULL,
	`shariaScore` decimal(5,2) NOT NULL,
	`legalScore` decimal(5,2) NOT NULL,
	`totalScore` decimal(5,2) NOT NULL,
	`classification` enum('Sangat Layak','Layak','Perlu Pengawasan','Tidak Layak') NOT NULL,
	`scoreBreakdown` json NOT NULL,
	`recommendations` text NOT NULL,
	`riskFactors` text,
	`strengths` text,
	`modelVersion` varchar(50) NOT NULL,
	`confidence` decimal(5,2),
	`assessedBy` int NOT NULL,
	`assessedAt` timestamp NOT NULL DEFAULT (now()),
	`notes` text,
	CONSTRAINT `assessments_id` PRIMARY KEY(`id`)
);
