import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Loader2, Shield } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";

const DRAFT_KEY = "ssci-new-application-draft-v1";
const steps = ["Nasabah", "Usaha & keuangan", "Legal & syariah", "ESG & tinjauan"];
type Document = { type: "KTP" | "NPWP" | "NIB"; status: "pending" | "complete" | "verified" | "missing"; notes: string };
type Values = Record<string, any> & { legalDocuments: Document[] };
const initial: Values = { customerName: "", customerId: "", businessName: "", businessType: "", businessAge: "", address: "", phone: "", email: "", monthlyRevenue: "", monthlyExpenses: "", existingDebt: "", collateralValue: "", requestedAmount: "", financingTenor: "", marginRate: "", loanPurpose: "", businessShariaCompliant: "", shariaComplianceNotes: "", environmentalPractices: "", socialImpact: "", governanceQuality: "", legalDocuments: [{ type: "KTP", status: "pending", notes: "" }, { type: "NPWP", status: "pending", notes: "" }, { type: "NIB", status: "pending", notes: "" }] };
const demoValues: Partial<Values>[] = [
  { customerName: "Budi Santoso Demo", customerId: "3273010101010001", phone: "081234567890", email: "budi.demo@example.test", address: "Jl. Contoh Demo No. 1, Kota Bandung" },
  { businessName: "Usaha Demo SSCI", businessType: "Perdagangan Demo", businessAge: "24", monthlyRevenue: "25000000", monthlyExpenses: "15000000", existingDebt: "2000000", collateralValue: "100000000", requestedAmount: "50000000", financingTenor: "24", marginRate: "10", loanPurpose: "Modal kerja untuk pengembangan Usaha Demo SSCI" },
  { legalDocuments: [{ type: "KTP", status: "complete", notes: "Dokumen demo untuk pengujian" }, { type: "NPWP", status: "complete", notes: "Dokumen demo untuk pengujian" }, { type: "NIB", status: "complete", notes: "Dokumen demo untuk pengujian" }], businessShariaCompliant: "yes", shariaComplianceNotes: "Catatan kepatuhan syariah demo untuk pengujian" },
  { environmentalPractices: "Menggunakan kemasan ramah lingkungan demo", socialImpact: "Menyediakan lapangan kerja lokal demo", governanceQuality: "good" },
];

function Field({ name, label, values, setValues, ...props }: { name: string; label: string; values: Values; setValues: React.Dispatch<React.SetStateAction<Values>>; [key: string]: unknown }) {
  const Component = props.rows ? Textarea : Input;
  return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Component id={name} name={name} value={String(values[name] || "")} onChange={(e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setValues(v => ({ ...v, [name]: e.target.value }))} {...props} /></div>;
}

export default function NewApplication() {
  const { user } = useAuth({ redirectOnUnauthenticated: true });
  const [, setLocation] = useLocation();
  const [values, setValues] = useState<Values>(initial);
  const [step, setStep] = useState(0);
  const [hasDraft, setHasDraft] = useState(false);
  const createMutation = trpc.applications.create.useMutation({ onSuccess: data => { localStorage.removeItem(DRAFT_KEY); toast.success("Aplikasi pembiayaan berhasil dibuat"); setLocation(`/applications/${data.id}`); }, onError: error => toast.error(`Gagal membuat aplikasi: ${error.message}`) });

  useEffect(() => { try { const saved = localStorage.getItem(DRAFT_KEY); if (saved) setHasDraft(true); } catch {} }, []);
  useEffect(() => { try { localStorage.setItem(DRAFT_KEY, JSON.stringify({ version: 1, values, step })); } catch {} }, [values, step]);
  const restore = () => { try { const saved = JSON.parse(localStorage.getItem(DRAFT_KEY) || ""); if (saved.version === 1) { setValues({ ...initial, ...saved.values }); setStep(Math.min(saved.step || 0, 3)); setHasDraft(false); } } catch { toast.error("Draft tidak dapat dipulihkan"); } };
  const reset = () => { localStorage.removeItem(DRAFT_KEY); setValues(initial); setStep(0); setHasDraft(false); };
  const fillDemo = (demoStep: number) => setValues(current => ({ ...current, ...demoValues[demoStep] } as Values));
  const fillAllDemo = () => setValues(current => demoValues.reduce<Values>((next, demo) => ({ ...next, ...demo }), current));
  const required: Record<number, string[]> = { 0: ["customerName", "customerId", "phone", "address"], 1: ["businessName", "businessType", "businessAge", "monthlyRevenue", "monthlyExpenses", "existingDebt", "collateralValue", "requestedAmount", "financingTenor", "marginRate", "loanPurpose"], 2: ["businessShariaCompliant"], 3: ["governanceQuality"] };
  const next = () => { const missing = required[step].filter(key => !String(values[key] || "").trim()); if (missing.length) { toast.error("Lengkapi semua kolom wajib sebelum melanjutkan"); document.getElementById(missing[0])?.focus(); return; } setStep(s => s + 1); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const submit = (e: React.FormEvent) => { e.preventDefault(); const missing = required[3].filter(key => !values[key]?.trim()); if (missing.length) return; createMutation.mutate({ customerName: values.customerName, customerId: values.customerId, businessName: values.businessName, businessType: values.businessType, businessAge: parseInt(values.businessAge), address: values.address, phone: values.phone, email: values.email || undefined, monthlyRevenue: values.monthlyRevenue, monthlyExpenses: values.monthlyExpenses, existingDebt: values.existingDebt, collateralValue: values.collateralValue, requestedAmount: values.requestedAmount, financingTenor: parseInt(values.financingTenor), marginRate: parseFloat(values.marginRate), loanPurpose: values.loanPurpose, legalDocuments: values.legalDocuments, businessShariaCompliant: values.businessShariaCompliant as "yes" | "no" | "partial", shariaComplianceNotes: values.shariaComplianceNotes || undefined, environmentalPractices: values.environmentalPractices || undefined, socialImpact: values.socialImpact || undefined, governanceQuality: values.governanceQuality as "excellent" | "good" | "fair" | "poor" }); };
  const select = (name: string, label: string, options: [string, string][]) => <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Select value={values[name]} onValueChange={value => setValues(v => ({ ...v, [name]: value }))}><SelectTrigger id={name}><SelectValue placeholder="Pilih" /></SelectTrigger><SelectContent>{options.map(([value, text]) => <SelectItem key={value} value={value}>{text}</SelectItem>)}</SelectContent></Select></div>;
  return <div className="min-h-screen bg-gray-50"><nav className="border-b bg-white"><div className="container flex items-center justify-between py-4"><Button variant="ghost" size="sm" asChild><Link href="/"><ArrowLeft className="mr-2 h-4 w-4" />Kembali</Link></Button><div className="flex items-center gap-2"><Shield className="h-6 w-6 text-primary" /><b className="text-xl text-primary">SSCI</b></div><span className="text-sm text-gray-600">{user?.name || ""}</span></div></nav>
     <main className="container max-w-4xl py-6 sm:py-8"><div className="mb-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-3xl font-bold text-gray-900">Aplikasi Pembiayaan Baru</h1><p className="mt-2 text-gray-600">Lengkapi data nasabah untuk penilaian kelayakan pembiayaan</p></div><Button type="button" variant="outline" onClick={fillAllDemo}>Isi Semua Contoh</Button></div><p className="mt-3 text-xs text-muted-foreground">Data demo hanya untuk pengujian dan tidak akan dikirim otomatis.</p></div>
      {hasDraft && <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm"><span>Draft tersimpan ditemukan.</span><span className="flex gap-2"><Button type="button" size="sm" onClick={restore}>Pulihkan draft</Button><Button type="button" size="sm" variant="ghost" onClick={reset}>Mulai ulang</Button></span></div>}
      <div className="mb-6"><div className="mb-2 flex justify-between text-sm font-medium"><span>Langkah {step + 1} dari 4</span><span>{steps[step]}</span></div><div className="flex gap-1">{steps.map((label, i) => <div key={label} className={`h-2 flex-1 rounded-full ${i <= step ? "bg-primary" : "bg-gray-200"}`} aria-label={label} />)}</div></div>
       <form onSubmit={submit}><Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>{steps[step]}</CardTitle><CardDescription>{step === 0 ? "Data identitas dan kontak nasabah" : step === 1 ? "Detail usaha dan kebutuhan pembiayaan" : step === 2 ? "Kelengkapan dokumen dan kepatuhan syariah" : "Dampak usaha dan pemeriksaan akhir"}</CardDescription></div><Button type="button" variant="outline" size="sm" onClick={() => fillDemo(step)}>Isi Contoh Demo</Button></div></CardHeader><CardContent className="space-y-4">
        {step === 0 && <><div className="grid gap-4 md:grid-cols-2"><Field name="customerName" label="Nama Lengkap *" values={values} setValues={setValues} required /><Field name="customerId" label="NIK / ID Nasabah *" values={values} setValues={setValues} required /><Field name="phone" label="Nomor Telepon *" values={values} setValues={setValues} type="tel" required /><Field name="email" label="Email (Opsional)" values={values} setValues={setValues} type="email" /></div><Field name="address" label="Alamat Lengkap *" values={values} setValues={setValues} rows={3} required /></>}
        {step === 1 && <><div className="grid gap-4 md:grid-cols-2"><Field name="businessName" label="Nama Usaha *" values={values} setValues={setValues} required /><Field name="businessType" label="Jenis Usaha *" values={values} setValues={setValues} required /><Field name="businessAge" label="Lama Usaha (bulan) *" values={values} setValues={setValues} type="number" min="1" required /><Field name="monthlyRevenue" label="Pendapatan Bulanan (Rp) *" values={values} setValues={setValues} type="number" min="0" required /><Field name="monthlyExpenses" label="Pengeluaran Bulanan (Rp) *" values={values} setValues={setValues} type="number" min="0" required /><Field name="existingDebt" label="Total Angsuran Existing per Bulan (Rp) *" values={values} setValues={setValues} type="number" min="0" required /><Field name="collateralValue" label="Nilai Agunan (Rp) *" values={values} setValues={setValues} type="number" min="0" required /><Field name="requestedAmount" label="Jumlah Pembiayaan (Rp) *" values={values} setValues={setValues} type="number" min="1" required /><Field name="financingTenor" label="Tenor Pembiayaan (bulan) *" values={values} setValues={setValues} type="number" min="1" required /><Field name="marginRate" label="Total Margin Akad (%) *" values={values} setValues={setValues} type="number" min="0" max="100" step="0.01" required /></div><Field name="loanPurpose" label="Tujuan Pembiayaan *" values={values} setValues={setValues} rows={3} required /></>}
        {step === 2 && <><div className="space-y-4"><div className="font-medium">Dokumen Legal</div>{values.legalDocuments.map((doc, i) => <div key={doc.type} className="grid items-end gap-3 md:grid-cols-3"><Input value={doc.type} disabled /><Select value={doc.status} onValueChange={status => setValues(v => ({ ...v, legalDocuments: v.legalDocuments.map((d, n) => n === i ? { ...d, status: status as Document["status"] } : d) }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{[["pending", "Pending"], ["complete", "Lengkap"], ["verified", "Terverifikasi"], ["missing", "Tidak Ada"]].map(([v, t]) => <SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select><Input placeholder="Catatan (opsional)" value={doc.notes} onChange={e => setValues(v => ({ ...v, legalDocuments: v.legalDocuments.map((d, n) => n === i ? { ...d, notes: e.target.value } : d) }))} /></div>)}</div>{select("businessShariaCompliant", "Kepatuhan Bisnis *", [["yes", "Ya, Sepenuhnya"], ["partial", "Sebagian"], ["no", "Tidak"]])}<Field name="shariaComplianceNotes" label="Catatan (Opsional)" values={values} setValues={setValues} rows={3} /></>}
        {step === 3 && <><Field name="environmentalPractices" label="Praktik Lingkungan (Opsional)" values={values} setValues={setValues} rows={2} /><Field name="socialImpact" label="Dampak Sosial (Opsional)" values={values} setValues={setValues} rows={2} />{select("governanceQuality", "Tata Kelola *", [["excellent", "Sangat Baik"], ["good", "Baik"], ["fair", "Cukup"], ["poor", "Kurang"]])}<p className="rounded-md bg-muted p-3 text-sm text-muted-foreground">Periksa kembali data sebelum mengirimkan aplikasi. Draft tersimpan otomatis di perangkat ini.</p></>}
      </CardContent></Card><div className="mt-6 flex gap-3">{step > 0 && <Button type="button" variant="outline" onClick={() => setStep(s => s - 1)}>Kembali</Button>}{step < 3 ? <Button type="button" className="ml-auto" onClick={next}>Lanjutkan</Button> : <Button type="submit" className="ml-auto" disabled={createMutation.isPending}>{createMutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Kirim Aplikasi</Button>}</div></form>
    </main></div>;
}
